### ISSUE TITLE
json: add allergen information

### ISSUE THREAD

**Issue by bertkenward** [tfrayner/beerfestdb#16]
It would be useful to have allergen information in the json output. Given allergen information is sometimes unknown I suggest allergens are presented as:
```
"allergens": {
  "gluten": true,
  "lupin": false
}
```
In this case we have no idea whether this product contains celery, or indeed any of the other allergens not listed. `true` would indicate the allergen is present.

In less there's a good reason to use other names - existing database names? - I suggest we use the following symbols.
```
eggs
milk
fish
crustaceans
molluscs
peanuts
treenuts
sesame
gluten
soya
celery
mustard
lupin
sulphur
```

**Comment by mah11** [comment]
Just one small quibble: I would use 'sulphites' (or 'sulfites' - IUPAC now recommends the 'f' spelling) rather than 'sulphur'. It's specifically the sulfite form that causes allergy-like problems, and some of the non-allergenic forms are either ubiquitous (e.g. anything that contains protein will have cysteine and methionine) or not an allergy issue (if anything has much sulfide it'll smell off to anyone, and if it's got elemental sulfur we've got bigger problems).

**Comment by bertkenward** [comment]
sul(ph|f)ites is fine by me. I suppose the IUPAC spelling will reduce the size of the json...

**Comment by tfrayner** [comment]
The JSON generating code now supports this. Note that the exact allergen terms which are used are defined in the product_allergen_type table. The terms are broadly similar but not exactly the same as specified above; if it's really critical to use those terms then the database will be the place to fix them.
